version: '3.0'
services:
  ts-starter:
    container_name: slack-radio
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./:/app
    ports:
      - 58587:58587
      - 58586:58586
      - 58585:58585
      - 8888:8888
